import { Employee, Team } from '../types';

export interface OfficialRecord {
  group: 'fat' | 'muscle';
  rank: number;
  empId: string;
  name: string;
  nickname: string;
  team: string;
  taskPts: number;
  rankPts: number;
  inbodyPts: number;
  totalPts: number;
  preVal: string;
  postVal: string;
  bodyResultStr: string;
  bodyResult: number;
  p22TargetStr: string;
  p22Target: number;
  isGoalMet: boolean;
  isMinPtsMet: boolean;
  achievementAward: boolean;
  achievementPrize: number;
  individualAward: string;
  individualAwardPrize: number;
  totalPersonalPrize: number;
}

export const OFFICIAL_SETTLEMENT_RECORDS: OfficialRecord[] = [
  // 減脂組 (43人)
  {
    group: 'fat',
    rank: 1,
    empId: 'VE0301',
    name: '鄭凱中',
    nickname: '沒意思',
    team: '無',
    taskPts: 175,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 190,
    preVal: '21.6%',
    postVal: '18.3%',
    bodyResultStr: '減脂 3.3%',
    bodyResult: 3.3,
    p22TargetStr: '減脂 3.3%',
    p22Target: 3.3,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '減脂組 冠軍 ($10,000)',
    individualAwardPrize: 10000,
    totalPersonalPrize: 12000,
  },
  {
    group: 'fat',
    rank: 2,
    empId: 'SM0012',
    name: '李芮綺',
    nickname: 'RRR',
    team: '第1組',
    taskPts: 169,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 189,
    preVal: '30.6%',
    postVal: '25.7%',
    bodyResultStr: '減脂 4.9% (增肌0.9kg)',
    bodyResult: 4.9,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '減脂組 亞軍 ($6,000)',
    individualAwardPrize: 6000,
    totalPersonalPrize: 8000,
  },
  {
    group: 'fat',
    rank: 3,
    empId: 'VE0128',
    name: '范紋綾',
    nickname: '失控的胖子',
    team: '第2組',
    taskPts: 171,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 186,
    preVal: '29%',
    postVal: '26%',
    bodyResultStr: '減脂 3%',
    bodyResult: 3.0,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '減脂組 季軍 ($3,000)',
    individualAwardPrize: 3000,
    totalPersonalPrize: 5000,
  },
  {
    group: 'fat',
    rank: 4,
    empId: 'SM0054',
    name: '柳季雯',
    nickname: 'Ava',
    team: '第1組',
    taskPts: 155,
    rankPts: 30,
    inbodyPts: 0,
    totalPts: 185,
    preVal: '39.3%',
    postVal: '34.4%',
    bodyResultStr: '減脂 4.9% (增肌1.7kg)',
    bodyResult: 4.9,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 5,
    empId: 'VE0297',
    name: '陳湘湘',
    nickname: '🐻🤓',
    team: '第5組',
    taskPts: 169,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 184,
    preVal: '41.7%',
    postVal: '38.3%',
    bodyResultStr: '減脂 3.4%',
    bodyResult: 3.4,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 6,
    empId: 'VE0266',
    name: '陳玟育',
    nickname: 'Mina',
    team: '第5組',
    taskPts: 160,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 175,
    preVal: '37.8%',
    postVal: '34.8%',
    bodyResultStr: '減脂 3%',
    bodyResult: 3.0,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 7,
    empId: 'SM0027',
    name: '張芷婷',
    nickname: '珍奶娜🧋',
    team: '第1組',
    taskPts: 158,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 173,
    preVal: '27.4%',
    postVal: '24.3%',
    bodyResultStr: '減脂 3.1%',
    bodyResult: 3.1,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 8,
    empId: 'VE0218',
    name: '戴妤庭',
    nickname: '戴油庭',
    team: '第5組',
    taskPts: 173,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 173,
    preVal: '34.9%',
    postVal: '33.7%',
    bodyResultStr: '減脂 1.2%',
    bodyResult: 1.2,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 9,
    empId: 'SM0052',
    name: '方宓菁',
    nickname: '蘇肥',
    team: '第1組',
    taskPts: 157,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 172,
    preVal: '28.9%',
    postVal: '26.4%',
    bodyResultStr: '減脂 2.5%',
    bodyResult: 2.5,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 10,
    empId: 'VE0219',
    name: '林聖傑',
    nickname: '蘆洲主委',
    team: '第7組',
    taskPts: 134,
    rankPts: 35,
    inbodyPts: 0,
    totalPts: 169,
    preVal: '20.8%',
    postVal: '15.8%',
    bodyResultStr: '減脂 5%',
    bodyResult: 5.0,
    p22TargetStr: '減脂 3.3%',
    p22Target: 3.3,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 11,
    empId: 'VE0221',
    name: '賴若宣',
    nickname: '小若',
    team: '第7組',
    taskPts: 140,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 155,
    preVal: '30.5%',
    postVal: '27.3%',
    bodyResultStr: '減脂 3.2%',
    bodyResult: 3.2,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 12,
    empId: 'VE0016',
    name: '張曉美',
    nickname: 'Hidomi',
    team: '第6組',
    taskPts: 155,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 155,
    preVal: '30%',
    postVal: '29.6%',
    bodyResultStr: '減脂 0.4%',
    bodyResult: 0.4,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 13,
    empId: 'VE0176',
    name: '許書銘',
    nickname: '豬銘',
    team: '第5組',
    taskPts: 148,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 148,
    preVal: '33.3%',
    postVal: '32.4%',
    bodyResultStr: '減脂 0.9%',
    bodyResult: 0.9,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 14,
    empId: 'VE0178',
    name: '周惠雯',
    nickname: 'deeeeeee',
    team: '第7組',
    taskPts: 123,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 138,
    preVal: '32%',
    postVal: '29%',
    bodyResultStr: '減脂 3%',
    bodyResult: 3.0,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 15,
    empId: 'VE0107',
    name: '劉冠萱',
    nickname: '背光向日葵',
    team: '無',
    taskPts: 132,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 132,
    preVal: '40.4%',
    postVal: '39.3%',
    bodyResultStr: '減脂 1.1%',
    bodyResult: 1.1,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 16,
    empId: 'VE0183',
    name: '徐慧玲',
    nickname: 'Pannie',
    team: '第3組',
    taskPts: 128,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 128,
    preVal: '32.3%',
    postVal: '32.1%',
    bodyResultStr: '減脂 0.2%',
    bodyResult: 0.2,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 17,
    empId: 'VE0226',
    name: '古秉翰',
    nickname: '咕咕咕',
    team: '第6組',
    taskPts: 121,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 121,
    preVal: '36.7%',
    postVal: '35.8%',
    bodyResultStr: '減脂 0.9%',
    bodyResult: 0.9,
    p22TargetStr: '減脂 3.3%',
    p22Target: 3.3,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 18,
    empId: 'VE0203',
    name: '簡辰芳',
    nickname: 'VE0203',
    team: '無',
    taskPts: 102,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 117,
    preVal: '44.7%',
    postVal: '42.1%',
    bodyResultStr: '減脂 2.6%',
    bodyResult: 2.6,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 19,
    empId: 'VE0288',
    name: '林姿妤',
    nickname: 'Joyce',
    team: '無',
    taskPts: 107,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 117,
    preVal: '28.4%',
    postVal: '26.7%',
    bodyResultStr: '減脂 1.7%',
    bodyResult: 1.7,
    p22TargetStr: '減脂 2.4%',
    p22Target: 2.4,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 20,
    empId: 'VE0034',
    name: '張丞萱',
    nickname: '阿芙',
    team: '第6組',
    taskPts: 112,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 112,
    preVal: '31.7%',
    postVal: '31.2%',
    bodyResultStr: '減脂 0.5%',
    bodyResult: 0.5,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 21,
    empId: 'VE0166',
    name: '洪淨珮',
    nickname: 'Peggy',
    team: '第3組',
    taskPts: 88,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 108,
    preVal: '32.4%',
    postVal: '28.9%',
    bodyResultStr: '減脂 3.5%',
    bodyResult: 3.5,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 22,
    empId: 'VE0181',
    name: '高敏敏',
    nickname: '喝酒誤事',
    team: '第2組',
    taskPts: 95,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 95,
    preVal: '26.9%',
    postVal: '27.1%',
    bodyResultStr: '減脂 -0.2%',
    bodyResult: -0.2,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 23,
    empId: 'VE0212',
    name: '曾毓萱',
    nickname: 'Lily',
    team: '無',
    taskPts: 74,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 94,
    preVal: '40.7%',
    postVal: '36.9%',
    bodyResultStr: '減脂 3.8%',
    bodyResult: 3.8,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 24,
    empId: 'VE0305',
    name: '黃靖雅',
    nickname: '蘿娜比娜',
    team: '無',
    taskPts: 52,
    rankPts: 40,
    inbodyPts: 0,
    totalPts: 92,
    preVal: '34.2%',
    postVal: '28.9%',
    bodyResultStr: '減脂 5.3%',
    bodyResult: 5.3,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'fat',
    rank: 25,
    empId: 'VE0005',
    name: '呂靈慧',
    nickname: '請你離開',
    team: '第6組',
    taskPts: 91,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 91,
    preVal: '33.7%',
    postVal: '32.4%',
    bodyResultStr: '減脂 1.3%',
    bodyResult: 1.3,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 26,
    empId: 'SM0046',
    name: '呂思佳',
    nickname: '阿拉斯加',
    team: '無',
    taskPts: 91,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 91,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 27,
    empId: 'VE0241',
    name: '張家獻',
    nickname: 'Allen',
    team: '無',
    taskPts: 89,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 89,
    preVal: '18.1%',
    postVal: '17.4%',
    bodyResultStr: '減脂 0.7%',
    bodyResult: 0.7,
    p22TargetStr: '減脂 3.3%',
    p22Target: 3.3,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 28,
    empId: 'SM0049',
    name: '林盈杏',
    nickname: 'Vk',
    team: '第6組',
    taskPts: 71,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 81,
    preVal: '30.9%',
    postVal: '28.9%',
    bodyResultStr: '減脂 2%',
    bodyResult: 2.0,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 29,
    empId: 'VE0287',
    name: '李季芹',
    nickname: '不能喝飲料',
    team: '第4組',
    taskPts: 67,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 77,
    preVal: '33.7%',
    postVal: '31.6%',
    bodyResultStr: '減脂 2.1%',
    bodyResult: 2.1,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 30,
    empId: 'VE0018',
    name: '林湘慈',
    nickname: 'Joanna',
    team: '無',
    taskPts: 63,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 63,
    preVal: '27%',
    postVal: '29%',
    bodyResultStr: '減脂 -2%',
    bodyResult: -2.0,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 31,
    empId: 'SM0005',
    name: '吳偲瑜',
    nickname: '🤫',
    team: '無',
    taskPts: 56,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 56,
    preVal: '38.9%',
    postVal: '37.6%',
    bodyResultStr: '減脂 1.3%',
    bodyResult: 1.3,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 32,
    empId: 'VE0265',
    name: '張初安',
    nickname: 'Kelly',
    team: '第3組',
    taskPts: 46,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 46,
    preVal: '31.3%',
    postVal: '30.3%',
    bodyResultStr: '減脂 1%',
    bodyResult: 1.0,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 33,
    empId: 'VE0028',
    name: '莫舒涵',
    nickname: 'Momo',
    team: '無',
    taskPts: 30,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 40,
    preVal: '35.6%',
    postVal: '33.2%',
    bodyResultStr: '減脂 2.4%',
    bodyResult: 2.4,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 34,
    empId: 'VE0233',
    name: '于智偉',
    nickname: '偉哥',
    team: '無',
    taskPts: 37,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 37,
    preVal: '37%',
    postVal: '36.4%',
    bodyResultStr: '減脂 0.6%',
    bodyResult: 0.6,
    p22TargetStr: '減脂 2.7%',
    p22Target: 2.7,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 35,
    empId: 'SM0063',
    name: '李蓓韻',
    nickname: '脂肪掰掰',
    team: '無',
    taskPts: 36,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 36,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 36,
    empId: 'VE0197',
    name: '陳緯浩',
    nickname: '浩浩',
    team: '無',
    taskPts: 20,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 20,
    preVal: '28.5%',
    postVal: '28.7%',
    bodyResultStr: '減脂 -0.2%',
    bodyResult: -0.2,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 37,
    empId: 'VE0008',
    name: '游智盛',
    nickname: '強森',
    team: '無',
    taskPts: 17,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 17,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 38,
    empId: 'SM0042',
    name: '李怡慧',
    nickname: 'Vera',
    team: '無',
    taskPts: 10,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 10,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 39,
    empId: 'SM0064',
    name: '陳育萱',
    nickname: '脂肪掰掰',
    team: '無',
    taskPts: 1,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 1,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 40,
    empId: 'VE0306',
    name: '顏劭宇',
    nickname: 'Annie',
    team: '無',
    taskPts: 1,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 1,
    preVal: '24.5%',
    postVal: '26.1%',
    bodyResultStr: '減脂 -1.6%',
    bodyResult: -1.6,
    p22TargetStr: '減脂 3%',
    p22Target: 3.0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 41,
    empId: 'VE0026',
    name: '林佳慧',
    nickname: 'E',
    team: '無',
    taskPts: 0,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 0,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 42,
    empId: 'VE0035',
    name: '鄭琦霏',
    nickname: '阿芙',
    team: '無',
    taskPts: 0,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 0,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'fat',
    rank: 43,
    empId: 'VE0240',
    name: '王素卿',
    nickname: '天使',
    team: '無',
    taskPts: 0,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 0,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },

  // 增肌組 (18人)
  {
    group: 'muscle',
    rank: 1,
    empId: 'SM0062',
    name: '張健威',
    nickname: '肯特',
    team: '第2組',
    taskPts: 167,
    rankPts: 35,
    inbodyPts: 0,
    totalPts: 202,
    preVal: '26.8kg',
    postVal: '28.2kg',
    bodyResultStr: '增肌 1.4kg (減脂1.2%)',
    bodyResult: 1.4,
    p22TargetStr: '增肌 1kg',
    p22Target: 1.0,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '增肌組 冠軍 ($10,000)',
    individualAwardPrize: 10000,
    totalPersonalPrize: 12000,
  },
  {
    group: 'muscle',
    rank: 2,
    empId: 'VE0296',
    name: '黃寶螢',
    nickname: 'Cindy',
    team: '第1組',
    taskPts: 123,
    rankPts: 40,
    inbodyPts: 0,
    totalPts: 163,
    preVal: '16.6kg',
    postVal: '18kg',
    bodyResultStr: '增肌 1.4kg (減脂3.0%)',
    bodyResult: 1.4,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '增肌組 亞軍 ($6,000)',
    individualAwardPrize: 6000,
    totalPersonalPrize: 8000,
  },
  {
    group: 'muscle',
    rank: 3,
    empId: 'VE0269',
    name: '鍾利羚',
    nickname: '好棒棒',
    team: '第1組',
    taskPts: 146,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 161,
    preVal: '18.1kg',
    postVal: '18.9kg',
    bodyResultStr: '增肌 0.8kg',
    bodyResult: 0.8,
    p22TargetStr: '增肌 0.6kg',
    p22Target: 0.6,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '增肌組 季軍 ($3,000)',
    individualAwardPrize: 3000,
    totalPersonalPrize: 5000,
  },
  {
    group: 'muscle',
    rank: 4,
    empId: 'VE0142',
    name: '方妍羽',
    nickname: 'Julia',
    team: '第1組',
    taskPts: 131,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 151,
    preVal: '17.6kg',
    postVal: '18.7kg',
    bodyResultStr: '增肌 1.1kg',
    bodyResult: 1.1,
    p22TargetStr: '增肌 0.6kg',
    p22Target: 0.6,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 5,
    empId: 'VE0300',
    name: '阮氏紅燕',
    nickname: 'Sylvia',
    team: '第1組',
    taskPts: 119,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 119,
    preVal: '17.8kg',
    postVal: '17.9kg',
    bodyResultStr: '增肌 0.1kg',
    bodyResult: 0.1,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 6,
    empId: 'VE0188',
    name: '廖婉妤',
    nickname: '葛蕾',
    team: '第2組',
    taskPts: 82,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 102,
    preVal: '21.8kg',
    postVal: '22.9kg',
    bodyResultStr: '增肌 1.1kg',
    bodyResult: 1.1,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 7,
    empId: 'VE0268',
    name: '徐淑貞',
    nickname: '貞',
    team: '無',
    taskPts: 76,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 96,
    preVal: '17.1kg',
    postVal: '18.2kg',
    bodyResultStr: '增肌 1.1kg',
    bodyResult: 1.1,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 8,
    empId: 'SM0001',
    name: '楊博鈞',
    nickname: 'Jonas',
    team: '無',
    taskPts: 72,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 87,
    preVal: '28.1kg',
    postVal: '29kg',
    bodyResultStr: '增肌 0.9kg',
    bodyResult: 0.9,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 9,
    empId: 'VE0276',
    name: '王靖惠',
    nickname: '拍',
    team: '無',
    taskPts: 63,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 78,
    preVal: '16.9kg',
    postVal: '17.7kg',
    bodyResultStr: '增肌 0.8kg',
    bodyResult: 0.8,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 10,
    empId: 'SM0073',
    name: '陳怡安',
    nickname: 'AnnChen',
    team: '無',
    taskPts: 45,
    rankPts: 30,
    inbodyPts: 0,
    totalPts: 75,
    preVal: '21.3kg',
    postVal: '22.5kg',
    bodyResultStr: '增肌 1.2kg',
    bodyResult: 1.2,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 11,
    empId: 'SM0033',
    name: '黃柔云',
    nickname: '~!@#$%^&',
    team: '無',
    taskPts: 45,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 65,
    preVal: '22.9kg',
    postVal: '23.9kg',
    bodyResultStr: '增肌 1kg',
    bodyResult: 1.0,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: true,
    isMinPtsMet: true,
    achievementAward: true,
    achievementPrize: 2000,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 2000,
  },
  {
    group: 'muscle',
    rank: 12,
    empId: 'VE0232',
    name: '蔡曉嵐',
    nickname: '肌不擇食',
    team: '第1組',
    taskPts: 53,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 63,
    preVal: '19.7kg',
    postVal: '19.9kg',
    bodyResultStr: '增肌 0.2kg',
    bodyResult: 0.2,
    p22TargetStr: '增肌 0.6kg',
    p22Target: 0.6,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 13,
    empId: 'VE0179',
    name: '吳冠蓁',
    nickname: 'jenny',
    team: '無',
    taskPts: 57,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 57,
    preVal: '21.4kg',
    postVal: '20.9kg',
    bodyResultStr: '增肌 -0.5kg',
    bodyResult: -0.5,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 14,
    empId: 'VE0171',
    name: '張翊君',
    nickname: '螺絲肌',
    team: '無',
    taskPts: 51,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 51,
    preVal: '18kg',
    postVal: '17.8kg',
    bodyResultStr: '增肌 -0.2kg',
    bodyResult: -0.2,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: false,
    isMinPtsMet: true,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 15,
    empId: 'VE0299',
    name: 'TRAN TRI BAO陳智寶',
    nickname: 'J',
    team: '無',
    taskPts: 6,
    rankPts: 0,
    inbodyPts: 20,
    totalPts: 26,
    preVal: '22.4kg',
    postVal: '23.4kg',
    bodyResultStr: '增肌 1kg',
    bodyResult: 1.0,
    p22TargetStr: '增肌 1kg',
    p22Target: 1.0,
    isGoalMet: true,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 16,
    empId: 'VE0278',
    name: '施惠菁',
    nickname: 'Brinaaa',
    team: '無',
    taskPts: 1,
    rankPts: 0,
    inbodyPts: 15,
    totalPts: 16,
    preVal: '26kg',
    postVal: '26.7kg',
    bodyResultStr: '增肌 0.7kg',
    bodyResult: 0.7,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 17,
    empId: 'VE0173',
    name: '鄭怡芳',
    nickname: '嘿九',
    team: '無',
    taskPts: 1,
    rankPts: 0,
    inbodyPts: 10,
    totalPts: 11,
    preVal: '23.9kg',
    postVal: '24.1kg',
    bodyResultStr: '增肌 0.2kg',
    bodyResult: 0.2,
    p22TargetStr: '增肌 0.8kg',
    p22Target: 0.8,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
  {
    group: 'muscle',
    rank: 18,
    empId: 'VE0304',
    name: '蘇采妍',
    nickname: '中年少女',
    team: '無',
    taskPts: 9,
    rankPts: 0,
    inbodyPts: 0,
    totalPts: 9,
    preVal: '未回填',
    postVal: '未回填',
    bodyResultStr: '未回填',
    bodyResult: 0,
    p22TargetStr: '-',
    p22Target: 0,
    isGoalMet: false,
    isMinPtsMet: false,
    achievementAward: false,
    achievementPrize: 0,
    individualAward: '無',
    individualAwardPrize: 0,
    totalPersonalPrize: 0,
  },
];

export const OFFICIAL_TEAMS_DATA: Team[] = [
  // 減脂組 7隊
  {
    id: 'fat-team-1',
    teamName: '第 1 組',
    group: 'fat',
    inviteCode: 'FAT01',
    leaderId: 'SM0012',
    members: ['SM0012', 'SM0027', 'SM0052', 'SM0054'],
  },
  {
    id: 'fat-team-2',
    teamName: '第 2 組',
    group: 'fat',
    inviteCode: 'FAT02',
    leaderId: 'VE0128',
    members: ['VE0128', 'VE0181'],
  },
  {
    id: 'fat-team-3',
    teamName: '第 3 組',
    group: 'fat',
    inviteCode: 'FAT03',
    leaderId: 'VE0183',
    members: ['VE0183', 'VE0166', 'VE0265'],
  },
  {
    id: 'fat-team-4',
    teamName: '第 4 組',
    group: 'fat',
    inviteCode: 'FAT04',
    leaderId: 'VE0287',
    members: ['VE0287'],
  },
  {
    id: 'fat-team-5',
    teamName: '第 5 組',
    group: 'fat',
    inviteCode: 'FAT05',
    leaderId: 'VE0297',
    members: ['VE0297', 'VE0266', 'VE0218', 'VE0176'],
  },
  {
    id: 'fat-team-6',
    teamName: '第 6 組',
    group: 'fat',
    inviteCode: 'FAT06',
    leaderId: 'VE0016',
    members: ['VE0016', 'VE0226', 'VE0034', 'VE0005', 'SM0049'],
  },
  {
    id: 'fat-team-7',
    teamName: '第 7 組',
    group: 'fat',
    inviteCode: 'FAT07',
    leaderId: 'VE0219',
    members: ['VE0178', 'VE0219', 'VE0221'],
  },

  // 增肌組 2隊
  {
    id: 'muscle-team-1',
    teamName: '第 1 組',
    group: 'muscle',
    inviteCode: 'MUS01',
    leaderId: 'VE0269',
    members: ['VE0142', 'VE0232', 'VE0269', 'VE0296', 'VE0300'],
  },
  {
    id: 'muscle-team-2',
    teamName: '第 2 組',
    group: 'muscle',
    inviteCode: 'MUS02',
    leaderId: 'SM0062',
    members: ['SM0062', 'VE0188'],
  },
];

/**
 * 將官方結算標準紀錄轉換為 Employee 模型物件
 */
export function convertOfficialRecordsToEmployees(): Employee[] {
  return OFFICIAL_SETTLEMENT_RECORDS.map((r) => {
    // 預設角色與性別依據
    const isMale = ['鄭凱中', '林聖傑', '許書銘', '古秉翰', '張家獻', '于智偉', '陳緯浩', '游智盛', '張健威', '楊博鈞', 'TRAN TRI BAO陳智寶'].includes(r.name);
    const gender = isMale ? 'male' : 'female';
    const ageGroup = ['范紋綾', '徐慧玲', '呂靈慧', '莫舒涵', '于智偉', '吳偲瑜', '張曉美', '李芮綺'].includes(r.name) ? 'age40to49' : 'under40';

    return {
      empId: r.empId,
      name: r.name,
      group: r.group,
      charId: r.group === 'fat' ? 'mage' : 'warrior',
      nickname: r.nickname,
      taskPts: r.taskPts,
      inbodyPts: r.inbodyPts,
      rankPts: r.rankPts,
      totalPts: r.totalPts,
      letters: ['S', 'H', 'I', 'N', 'Y', 'B', 'R', 'A', 'N', 'D', 'S'].slice(0, Math.min(11, Math.floor(r.totalPts / 8))),
      target: r.group === 'fat' ? '體脂率下降' : '骨骼肌重增加',
      targetVal: r.p22Target,
      currentGap: Math.max(0, parseFloat((r.p22Target - r.bodyResult).toFixed(2))),
      consecutiveDays: Math.min(30, Math.floor(r.taskPts / 5)),
      jellyCount: Math.min(4, Math.floor(r.taskPts / 40)),
      weeklyDiet: Math.min(7, Math.floor(r.taskPts / 20)),
      weeklySport: Math.min(5, Math.floor(r.taskPts / 30)),
      weeklyHealth: Math.min(5, Math.floor(r.taskPts / 30)),
      lastWeek: 6,
      lastDietDate: '2026-08-27',
      gender,
      ageGroup,
      bodyResult: r.bodyResult,
      p22Target: r.p22Target,
      isGoalMet: r.isGoalMet,
      isMinPtsMet: r.isMinPtsMet,
      achievementAward: r.achievementAward,
      individualAward: r.individualAward === '無' ? undefined : r.individualAward,
      individualAwardPrize: r.individualAwardPrize,
    };
  });
}
